version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=B1zcuitS3crEt!
      - POSTGRES_USER=bizcuit_user
      - POSTGRES_DB=bizcuit_db