import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import type { Metadata } from 'next'
import Container from '@mui/material/Container'
import Box from '@mui/material/Box'
import { AppBar, Link, Toolbar } from '@mui/material'
import { Providers } from '../providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Container>
            <AppBar>
              <Toolbar>
                <Link color="inherit" href="/sign-out">Sign out</Link>
              </Toolbar>
            </AppBar>
            <Box
              sx={{
                flexGrow: 1,
                bgcolor: 'background.default',
                mt: ['48px', '56px', '64px'],
                p: 3,
              }}
            >  
              <Providers>
                {children}
              </Providers> 
            </Box>
          </Container>
        </ThemeRegistry>
      </body>
    </html>
  )
}
